#!/bin/sh
set -eu

mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_BOOK_USER}'@'%' IDENTIFIED BY '${MYSQL_BOOK_PASSWORD}';
GRANT ALL PRIVILEGES ON books.* TO '${MYSQL_BOOK_USER}'@'%';
CREATE DATABASE IF NOT EXISTS audit;
CREATE USER IF NOT EXISTS '${MYSQL_AUDIT_USER}'@'%' IDENTIFIED BY '${MYSQL_AUDIT_PASSWORD}';
GRANT ALL PRIVILEGES ON audit.* TO '${MYSQL_AUDIT_USER}'@'%';
FLUSH PRIVILEGES;
SQL
