#!/bin/sh
set -eu

MYSQL_PWD="${MYSQL_ROOT_PASSWORD}" mysql -uroot <<SQL
CREATE USER IF NOT EXISTS '${MYSQL_BOOK_USER}'@'%' IDENTIFIED BY '${MYSQL_BOOK_PASSWORD}';
GRANT ALL PRIVILEGES ON books.* TO '${MYSQL_BOOK_USER}'@'%';
CREATE DATABASE IF NOT EXISTS books_testing;
CREATE USER IF NOT EXISTS '${MYSQL_BOOK_TEST_USER}'@'%' IDENTIFIED BY '${MYSQL_BOOK_TEST_PASSWORD}';
GRANT ALL PRIVILEGES ON books_testing.* TO '${MYSQL_BOOK_TEST_USER}'@'%';
CREATE DATABASE IF NOT EXISTS audit;
CREATE USER IF NOT EXISTS '${MYSQL_AUDIT_USER}'@'%' IDENTIFIED BY '${MYSQL_AUDIT_PASSWORD}';
GRANT ALL PRIVILEGES ON audit.* TO '${MYSQL_AUDIT_USER}'@'%';
FLUSH PRIVILEGES;
SQL
